name: 'Cache'
description: 'Optimised installation and caching of npm dependencies to improve workflow execution time'
author: 'Trilogy'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
inputs:
  target:
    description: 'subfolder with the project'
    required: false
    default: '.'
