name: Verify

on:
  workflow_dispatch:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          subfolder: test/node12
      - uses: ./
        with:
          subfolder: test/node16
      - uses: ./
        with:
          subfolder: test/ci-all
