name: Verify

on:
  workflow_dispatch:
  pull_request:

jobs:
  run:
    name: test ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [node12, node16, ci-all]
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: ./
        with:
          subfolder: test/${{ matrix.version }}
      - run: cd test/${{ matrix.version }} && npm run test
